apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-community
  labels:
    app: hello-community
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello-community
  template:
    metadata:
      labels:
        app: hello-community
    spec:
      containers:
      - name: hello-community
        image: ghcr.io/sap-samples/sap-community-code-challenge-cloud-native:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8080
      imagePullSecrets:
      - name: regcred
---
apiVersion: v1
kind: Service
metadata:
  name: hello-community
spec:
  selector:
    app: hello-community
  ports:
  - port: 8080
    targetPort: 8080

---
apiVersion: gateway.kyma-project.io/v1alpha1
kind: APIRule
metadata:
  name: hello-community
spec:
  gateway: kyma-gateway.kyma-system.svc.cluster.local
  service:
    name: hello-community
    port: 8080
    host: hello-community
  rules:
    - path: /.*
      methods: ["GET"]
      accessStrategies:
        - handler: noop
          config: {}
